"""add status column to itinerary tables

Revision ID: 97562ea9b503
Revises: b7342022651d
Create Date: 2025-08-04 18:58:12.966231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97562ea9b503'
down_revision: Union[str, Sequence[str], None] = 'b7342022651d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'status')
    # ### end Alembic commands ###
