"""add description column to itinerary tables

Revision ID: bcd5fad2691d
Revises: 97562ea9b503
Create Date: 2025-08-07 16:56:00.689369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcd5fad2691d'
down_revision: Union[str, Sequence[str], None] = '97562ea9b503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'description')
    # ### end Alembic commands ###
