"""update date column name to itinerary tables

Revision ID: c14e6f026428
Revises: bcd5fad2691d
Create Date: 2025-08-07 17:10:54.095722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c14e6f026428'
down_revision: Union[str, Sequence[str], None] = 'bcd5fad2691d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_days', sa.Column('day', sa.Date(), nullable=True))
    op.drop_column('plan_days', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_days', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('plan_days', 'day')
    # ### end Alembic commands ###
